#
# LoRa
#

obj-$(CONFIG_LORA_DEV) += lora-dev.o
lora-dev-y := dev.o

#
# Alphabetically sorted.
#

obj-$(CONFIG_LORA_RN2483) += lora-rn2483.o
lora-rn2483-y := rn2483.o
lora-rn2483-y += rn2483_cmd.o

obj-$(CONFIG_LORA_SX1276) += lora-sx1276.o
lora-sx1276-y := sx1276.o
