#
# LoRa
#

obj-$(CONFIG_LORA_DEV) += lora-dev.o
lora-dev-y := dev.o

#
# Alphabetically sorted.
#

obj-$(CONFIG_LORA_RAK811) += lora-rak811.o
lora-rak811-y := rak811.o

obj-$(CONFIG_LORA_RN2483) += lora-rn2483.o
lora-rn2483-y := rn2483.o
lora-rn2483-y += rn2483_cmd.o

obj-$(CONFIG_LORA_SX1257) += lora-sx1257.o
lora-sx1257-y := sx1257.o

obj-$(CONFIG_LORA_SX1276) += lora-sx1276.o
lora-sx1276-y := sx1276.o

obj-$(CONFIG_LORA_USI) += lora-usi.o
lora-usi-y := usi.o

obj-$(CONFIG_LORA_WIMOD) += lora-wimod.o
lora-wimod-y := wimod.o
